services:
  db:
    image: mysql:8.0
    container_name: portfolio-db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3309:3309"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: portfolio-api
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      WEB_ORIGIN: http://localhost:3000
    ports:
      - "3333:3333"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_GITHUB_URL: ${NEXT_PUBLIC_GITHUB_URL}
        NEXT_PUBLIC_LINKEDIN_URL: ${NEXT_PUBLIC_LINKEDIN_URL}
        NEXT_PUBLIC_EMAIL: ${NEXT_PUBLIC_EMAIL}
        NEXT_PUBLIC_FORMSPREE_ENDPOINT: ${NEXT_PUBLIC_FORMSPREE_ENDPOINT}
        API_INTERNAL_URL: ${API_INTERNAL_URL}
    environment:
      API_INTERNAL_URL: ${API_INTERNAL_URL}
    container_name: portfolio-web
    restart: unless-stopped
    env_file: .env
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  mysql_data:
